### ISSUE TITLE
Zulip exited with code 1(stuck while waiting for DB connections)

### ISSUE THREAD

**Issue by deevant07** [Galexrt/docker-zulip#51]
Hi, I am not sure if the problem is with config but i am newbie to zulip and docker.

The docker-compose.yml is configured as below.
```
database:
  image: "galexrt/zulip-postgresql-tsearchextras:latest"
  environment:
    DB_NAME: zulip
    DB_USER: zulip
    DB_PASS: zulip
  volumes:
    - "/opt/docker/zulip/postgresql/data:/var/lib/postgresql:rw"
memcached:
  image: "sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "rabbitmq:3.5.5"
  hostname: zulip-rabbit
  restart: always
  environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "zulip"
redis:
  image: "sameersbn/redis:latest"
  volumes:
    - "/opt/docker/zulip/redis:/var/lib/redis:rw"
zulip:
  image: "galexrt/zulip:1.3.7-2"
  ports:
    - "8081:8080"
    - "8443:443"
  links:
    - database
    - memcached
    - rabbitmq
    - redis
  environment:
   ZULIP_SETTINGS_EXTERNAL_HOST: "domain.com"
   ZULIP_SETTINGS_ZULIP_ADMINISTRATOR: "user@domain.com"
   ZULIP_SETTINGS_ADMIN_DOMAIN: "domain.com"
   ZULIP_SETTINGS_NOREPLY_EMAIL_ADDRESS: "noreply@domain.com"
   ZULIP_SETTINGS_DEFAULT_FROM_EMAIL: "Zulip <noreply@domain.com>"
   ZULIP_SETTINGS_EMAIL_HOST: "10.102.50.235"
   ZULIP_SETTINGS_EMAIL_HOST_USER: "testuser"
   ZULIP_SETTINGS_EMAIL_HOST_PASSWORD: "xxxx" 
   ZULIP_USER_EMAIL: "test@test.com"
   ZULIP_USER_PASS: "xxxx"
   ZULIP_USER_DOMAIN: "example.com"
  volumes:
    - "/opt/docker/zulip/zulip:/data:rw"
```
The part of the log file which highlights the problem is as follows.
```
zulip_1     | Setting database configuration ...
zulip_1     | Setting key "DATABASES", type "array".
zulip_1     | Database configuration succeeded.
zulip_1     | Setting caches configuration ...
zulip_1     | Setting key "CACHES", type "array".
zulip_1     | Caches configuration succeeded.
zulip_1     | Activating authentication backends ...
zulip_1     | Setting key "AUTHENTICATION_BACKENDS", type "array".
zulip_1     | Adding authentication backend "EmailAuthBackend".
zulip_1     | Authentication backend activation succeeded.
zulip_1     | Setting redis configuration ...
zulip_1     | Setting key "RATE_LIMITING", type "bool".
zulip_1     | Setting key "REDIS_HOST", type "string".
zulip_1     | Setting key "REDIS_HOST_PORT", type "int".
zulip_1     | Redis configuration succeeded.
zulip_1     | Setting rabbitmq configuration ...
zulip_1     | Setting key "RABBITMQ_HOST", type "string".
zulip_1     | Setting key "RABBITMQ_USERNAME", type "string".
zulip_1     | Rabbitmq configuration succeeded.
zulip_1     | Executing Zulip configuration ...
zulip_1     | Setting key "EMAIL_HOST_USER", type "string".
zulip_1     | Setting key "NOREPLY_EMAIL_ADDRESS", type "string".
zulip_1     | Setting key "EMAIL_HOST", type "string".
zulip_1     | Setting key "EXTERNAL_HOST", type "string".
zulip_1     | Setting key "EMAIL_HOST_PASSWORD", type "string".
zulip_1     | Setting key "ADMIN_DOMAIN", type "string".
zulip_1     | Setting key "DEFAULT_FROM_EMAIL", type "string".
zulip_1     | Setting key "ZULIP_ADMINISTRATOR", type "string".
zulip_1     | Zulip configuration succeeded.
zulip_1     | Auto backup enabled.
zulip_1     | === End Initial Configuration Phase ===
zulip_1     | === Begin Bootstrap Phase ===
zulip_1     | Waiting for database server to allow connections ...
zulip_1     | ...........................................................openstack_zulip_1 exited with code 1
```

Detailed log file is attached.

Kindly help in resolving the problem.

I am using the command sudo docker-compose up
[docker-zulip.txt](https://github.com/Galexrt/docker-zulip/files/45649/docker-zulip.txt)
