### ISSUE TITLE
Database error: relation "zerver_realmfilter" does not exist at character 146

### ISSUE THREAD

**Issue by metamorphious** [galexrt/docker-zulip#66]
I just had a running container, stopped it for changing some settings. Now I can't get it running again because of the database errors. I already tried to delete all database and zulip data. Even deleted all docker images and pulled again. Have the same errors.

Side question: Do I need your complete git repo or just the docker-compose.yml file?

docker-compose.yml:
```
database:
  image: "quay.io/galexrt/zulip-postgresql-tsearchextras:latest"
  environment:
    DB_NAME: zulip
    DB_USER: zulip
    DB_PASS: zulip2
  volumes:
    - "/opt/docker/zulip/postgresql/data:/var/lib/postgresql:rw"
memcached:
  image: "quay.io/sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "rabbitmq:3.5.5"
  hostname: zulip-rabbit
  restart: always
  environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "zulip1"
redis:
  image: "quay.io/sameersbn/redis:latest"
  volumes:
    - "/opt/docker/zulip/redis:/var/lib/redis:rw"
zulip:
  image: "quay.io/galexrt/zulip:v1.3.10"
  ports:
    - "8080:80"
    - "443:443"
  links:
    - database
    - memcached
    - rabbitmq
    - redis
  environment:
    DB_HOST: "database"
    DB_USER: "zulip"
    DB_PASS: "zulip2"
    SECRETS_email_password: "123456789"
    SECRETS_rabbitmq_password: "zulip1"
    SETTING_MEMCACHED_LOCATION: "memcached:11211"
    SETTING_RABBITMQ_HOST: "rabbitmq"
    SETTING_REDIS_HOST: "redis"
    SETTING_EXTERNAL_HOST: "team.my-domain.com"
    SETTING_ZULIP_ADMINISTRATOR: "admin@my-domain.com"
    SETTING_ADMIN_DOMAIN: "my-domain.com"
    SETTING_NOREPLY_EMAIL_ADDRESS: "noreply@my-domain.com"
    SETTING_DEFAULT_FROM_EMAIL: "Zulip <noreply@my-domain.com>"
    SETTING_EMAIL_HOST: "smtp.my-domain.com"
    SETTING_EMAIL_HOST_USER: "noreply@my-domain.com"
    ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
    ZULIP_USER_EMAIL: "example@my-domain.com"
    ZULIP_USER_PASS: "zulip"
    ZULIP_USER_DOMAIN: "my-domain.com"
  volumes:
    - "/opt/docker/zulip/zulip:/data:rw"
```

Log:
```
zulip_1     | 2016-04-23 15:02:40,693 INFO exited: zulip-postsetup-create_user (exit status 127; expected)
database_1  | ERROR:  relation "zerver_scheduledjob" does not exist at character 219
database_1  | STATEMENT:  SELECT "zerver_scheduledjob"."id", "zerver_scheduledjob"."scheduled_timestamp", "zerver_scheduledjob"."type", "zerver_scheduledjob"."data", "zerver_scheduledjob"."filter_id", "zerver_scheduledjob"."filter_string" FROM "zerver_scheduledjob" WHERE ("zerver_scheduledjob"."type" = 1 AND "zerver_scheduledjob"."scheduled_timestamp" <= '2016-04-23T15:02:44.123130-04:00'::timestamptz)
zulip_1     | 2016-04-23 15:02:44,755 INFO exited: zulip-deliver-enqueued-emails (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:45,760 INFO spawned: 'zulip-deliver-enqueued-emails' with pid 174
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
database_1  | ERROR:  relation "zerver_realmfilter" does not exist at character 146
database_1  | STATEMENT:  SELECT "zerver_realmfilter"."id", "zerver_realmfilter"."realm_id", "zerver_realmfilter"."pattern", "zerver_realmfilter"."url_format_string" FROM "zerver_realmfilter"
zulip_1     | 2016-04-23 15:02:47,077 INFO success: zulip-deliver-enqueued-emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1     | 2016-04-23 15:02:47,078 INFO exited: zulip-events-slowqueries (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,082 INFO spawned: 'zulip-events-slowqueries' with pid 178
zulip_1     | 2016-04-23 15:02:47,082 INFO exited: zulip-events-user-presence (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,093 INFO spawned: 'zulip-events-user-presence' with pid 179
zulip_1     | 2016-04-23 15:02:47,099 INFO exited: zulip-events-message_sender-3 (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,107 INFO spawned: 'zulip-events-message_sender-3' with pid 180
zulip_1     | 2016-04-23 15:02:47,111 INFO exited: zulip-tornado (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,111 INFO exited: zulip-events-user-activity (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,123 INFO spawned: 'zulip-tornado' with pid 181
zulip_1     | 2016-04-23 15:02:47,128 INFO spawned: 'zulip-events-user-activity' with pid 182
zulip_1     | 2016-04-23 15:02:47,129 INFO exited: zulip-events-message_sender-2 (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,131 INFO exited: zulip-events-feedback_messages (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,142 INFO exited: zulip-events-signups (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,145 INFO exited: zulip-events-email_mirror (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,145 INFO exited: zulip-events-missedmessage_reminders (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,154 INFO spawned: 'zulip-events-message_sender-2' with pid 183
zulip_1     | 2016-04-23 15:02:47,166 INFO spawned: 'zulip-events-email_mirror' with pid 184
zulip_1     | 2016-04-23 15:02:47,179 INFO spawned: 'zulip-events-signups' with pid 185
zulip_1     | 2016-04-23 15:02:47,182 INFO spawned: 'zulip-events-missedmessage_reminders' with pid 186
zulip_1     | 2016-04-23 15:02:47,192 INFO spawned: 'zulip-events-feedback_messages' with pid 187
zulip_1     | 2016-04-23 15:02:47,192 INFO exited: zulip-events-message_sender-4 (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,192 INFO exited: zulip-events-message_sender-0 (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-message_sender-1 (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-error_reports (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-user-activity-interval (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-confirmation-emails (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-missedmessage_mobile_notifications (exit status 1; not expected)
zulip_1     | 2016-04-23 15:02:47,193 INFO exited: zulip-events-digest_emails (exit status 1; not expected)
```
