### ISSUE TITLE
Nginx won't start, if forced, shows Zulip error 500

### ISSUE THREAD

**Issue by vegbrasil** [galexrt/docker-zulip#81]
Hi,

I'm having some problems with the startup process, here's what's happening:

When `docker-compose up -d`, everything seems ok:

```
root@ecs:/home/linux# docker-compose up -d
Starting linux_rabbitmq_1
Starting linux_memcached_1
Starting linux_zulip_1
Starting linux_redis_1
Starting linux_database_1
``` 
Every container starts and most importantly, stays up. The problem is that nothing happens, no HTTP/HTTPS request is served - if I bash into the Zulip container, `/var/log/zulip/install.log` says the installation was complete. `/var/log/nginx/error.log` shows nothing. Using `service nginx start`, the configured domain shows Zulip's error 500 page. 

After manually starting Nginx, this is what is shown in the logs:

```
2017/03/23 18:59:54 [crit] 214#0: *6 connect() to unix:/home/zulip/deployments/uwsgi-socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.115, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/zulip/deployments/uwsgi-socket:", host: "app.mycompany.com"
```

My `docker-compose.yml` is like this:

```
version: '2'
services:
  database:
    image: "quay.io/galexrt/zulip-postgresql-tsearchextras:latest"
    environment:
      DB_NAME: zulip
      DB_USER: zulip
      DB_PASS: zulip
    volumes:
      - "/opt/docker/zulip/postgresql/data:/var/lib/postgresql:rw"
  memcached:
    image: "quay.io/sameersbn/memcached:latest"
    restart: always
  rabbitmq:
    image: "rabbitmq:3.5.5"
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: "zulip"
        RABBITMQ_DEFAULT_PASS: "zulip"
  redis:
    image: "quay.io/sameersbn/redis:latest"
    volumes:
      - "/opt/docker/zulip/redis:/var/lib/redis:rw"
  zulip:
    image: "quay.io/galexrt/zulip:1.5.1"
    command:
    - sleep
    - "3600"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: "database"
      DB_USER: "zulip"
      DB_PASS: "zulip"
      DB_PASS: "zulip"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: "mypassword"
      SECRETS_rabbitmq_password: "zulip"
      SETTING_EXTERNAL_HOST: "app.mycompany.com"
      SETTING_ZULIP_ADMINISTRATOR: "vinicius@mycompany.com"
      SETTING_ADMIN_DOMAIN: "app.mycompany.com"
      SETTING_NOREPLY_EMAIL_ADDRESS: "noreply@app.mycompany.com"
      SETTING_DEFAULT_FROM_EMAIL: "Zulip <noreply@app.mycompany.com>"
      SETTING_EMAIL_HOST: "mail.mycompany.com"
      SETTING_EMAIL_HOST_USER: "vincius@mycompany.com"
      SETTING_ALLOWED_HOSTS: "[ '*', '127.0.0.2' ]"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      ZULIP_USER_CREATION_ENABLED: "True"
      ZULIP_USER_EMAIL: "vinicius@mycompany.com"
      ZULIP_USER_PASS: "inter"
      ZULIP_USER_DOMAIN: "app.mycompany.com"
      ZULIP_USER_FULLNAME: "Vinícius Santana"
    volumes:
      - "/opt/docker/zulip/zulip:/data:rw"
      - "/etc/ssl/:/etc/ssl/"
```
`mail.mycompany.com` is a fully functional SMTP server and `app.mycompany.com` is pointed to the server running the containers.

Thanks a lot!
