### ISSUE TITLE
1.5.1-4 Error: You must set NOREPLY_EMAIL_ADDRESS

### ISSUE THREAD

**Issue by huneau** [galexrt/docker-zulip#82]
Hi, 

I've got this error when I try to use your docker without any configuration:
```
zulip_1      | Error: You must set NOREPLY_EMAIL_ADDRESS in /etc/zulip/settings.py.
dockerzulip_zulip_1 exited with code 1
```

Did I miss something? 

I just git clone ...\ docker-compose up

**Comment by galexrt** [comment]
You need to configure the `docker-compose.yml`.
See https://github.com/galexrt/docker-zulip#configure-your-docker-composeyml-before-running-the-container and the wiki page linked at it.

**Comment by huneau** [comment]
Hum, All custom settings is already set in your docker-compose.yml.

``` yaml
    environment:
      DB_HOST: "database"
      DB_USER: "zulip"
      DB_PASS: "zulip"
      DB_PASS: "zulip"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: "123456789"
      SECRETS_rabbitmq_password: "zulip"
      SECRETS_secret_key: "REPLCAE_WITH_SECURE_SECRET_KEY"
      SETTING_EXTERNAL_HOST: "example.com"
      SETTING_ZULIP_ADMINISTRATOR: "admin@example.com"
      SETTING_ADMIN_DOMAIN: "example.com"
      ###################HERE###################
      SETTING_NOREPLY_EMAIL_ADDRESS: "noreply@example.com"
      ##########################################
      SETTING_DEFAULT_FROM_EMAIL: "Zulip <noreply@example.com>"
      SETTING_EMAIL_HOST: "smtp.example.com"
      SETTING_EMAIL_HOST_USER: "noreply@example.com"
      SETTING_EMAIL_PORT: "587"
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"
      SETTING_ALLOWED_HOSTS: "[ '*', '127.0.0.2' ]"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      ZULIP_USER_CREATION_ENABLED: "True"
      ZULIP_USER_EMAIL: "example@example.com"
      ZULIP_USER_PASS: "zulip"
      ZULIP_USER_DOMAIN: "example.com"
```
