### ISSUE TITLE
Problems with Traefik as proxy

### ISSUE THREAD

**Issue by Rinma** [galexrt/docker-zulip#94]
Hello,
I try to get zulip container work with Traefik. My problem is I get the error `The page isn’t redirecting properly` when i try to use it. But when I set up port mapping with docker-compose I can see that zulip is working fine. So it is only a configuration issue with Traefik and I hope someone have an idea.

docker-compose.yml
```
version: '3.4'
services:
  database:
    image: "quay.io/galexrt/postgres-zulip-tsearchextras:latest"
    restart: unless-stopped
    environment:
      POSTGRES_DB: zulip
      POSTGRES_USER: zulip
      POSTGRES_PASSWORD: zulip
    volumes:
    - "/var/data/chat/postgres_data:/var/lib/postgresql/data:rw"
    networks:
    - chat_net

  memcached:
    image: "quay.io/sameersbn/memcached:latest"
    restart: unless-stopped
    networks:
    - chat_net

  rabbitmq:
    image: "rabbitmq:3.5.5"
    hostname: zulip-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "zulip"
    networks:
    - chat_net

  redis:
    image: "quay.io/sameersbn/redis:latest"
    restart: unless-stopped
    volumes:
    - "/var/data/chat/redis:/var/lib/redis:rw"
    networks:
    - chat_net

  zulip:
    image: "quay.io/galexrt/zulip:1.7.1-0"
    restart: unless-stopped
    labels:
    - "traefik.docker.network=proxy_traefik_net"
    - "traefik.frontend.rule=Host:chat.example.org"
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.default.protocol=http"
    environment:
      DB_HOST: "database"
      DB_HOST_PORT: "5432"
      DB_USER: "zulip"
      DB_PASS: "zulip"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: "*****************"
      SECRETS_rabbitmq_password: "zulip"
      SECRETS_secret_key: "Secret_key_value"
      SETTING_EXTERNAL_HOST: "chat.example.org"
      SETTING_ADMIN_DOMAIN: "example.org"
      SETTING_ZULIP_ADMINISTRATOR: "admin@example.org"
      SETTING_NOREPLY_EMAIL_ADDRESS: "noreply@example.org"
      SETTING_DEFAULT_FROM_EMAIL: "Zulip <noreply@example.org>"
      SETTING_EMAIL_HOST: "smtp.example.org"
      SETTING_EMAIL_HOST_USER: "email@example.org"
      SETTING_EMAIL_PORT: "587"
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"
      SETTING_ALLOWED_HOSTS: "[ 'chat.example.org', '127.0.0.1' ]"
      SETTING_USE_X_FORWARDED_HOST: "True"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      DISABLE_HTTPS: "True"
    volumes:
    - "/var/data/chat/data:/data:rw"
    ports:
    - "0.0.0.0:5080:80"
    - "0.0.0.0:5043:443"
    networks:
    - chat_net
    - proxy_traefik_net

networks:
  chat_net:
    driver: bridge
  proxy_traefik_net:
    external: true
```

The configuration in the `labels` section of the compose file is for configure Traefik. It says that the url is `chat.example.org` and it should talk to the container on port `80` with the `http` protocol. Traefik is issuing Let's Encrypt certifactes for https and serves the url only under https.
